In [60]:
import pandas as pd
import numpy as np

In [61]:
a = np.arange(0,11,2)
print(a)

[ 0  2  4  6  8 10]


In [62]:
#ex1 
a = np.arange(0,20,3)
a

array([ 0,  3,  6,  9, 12, 15, 18])

In [63]:
b = np.arange(0,16).reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
mat3 = np.arange(20).reshape(4, 5)
print(mat3)
mat3[:,1:3]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [65]:
mat4 = np.arange(9).reshape(3, 3)
mat4


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
mat4[:,0]


array([0, 3, 6])

In [67]:
#Broadcasting
mat5 = np.ones((3,4))
vec5 = np.array([1, 2, 3, 4]).reshape((1,4))
print(vec5.shape)
print(mat5.shape)
mat5 + vec5

(1, 4)
(3, 4)


array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [68]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = "int32")
col_mean = mat.mean(axis = 0)
col_mean 

array([4., 5., 6.])

In [69]:
arr7 = np.array([3, 15, 8, 22, 6, 11, 1])
arr7[arr7>10] = 0
arr7

array([3, 0, 8, 0, 6, 0, 1])

In [70]:
index = [1,3,5]
arr8 = np.array([100, 200, 300, 400, 500, 600, 700])
arr8[index]

array([200, 400, 600])

In [71]:
a1 = np.array([[1,2],[3,4]])
b1 =np.array([[1,2],[3,4]])
a1*b1
a1@b1
np.matmul(a1,b1)

array([[ 7, 10],
       [15, 22]])

In [72]:
#Stacking arrays 
x1 = np.array([1,2,3])
x2 = np.array([4,5,6])
#vertical stacking of arrays 

np.hstack((x1,x2))

array([1, 2, 3, 4, 5, 6])

In [75]:
a = np.array([[1,2,3],[4,5,6]])
a.resize((3,2))
a

array([[1, 2],
       [3, 4],
       [5, 6]])